### ISSUE TITLE
Resource ["File", "/var/lib/rundeck/libext"] already declared

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#77] opened 2015-05-25 04:45 UTC
Got this error message, when try to set the plugin via hiera yaml file:

```
Error: Failed to apply catalog: Cannot alias File[/var/lib/rundeck/libext/] to ["/var/lib/rundeck/libext"] at /etc/puppet/environments/devtest_coreaws_MC_2230/dist/modules/rundeck/manifests/config/plugin.pp:77; resource ["File", "/var/lib/rundeck/libext"] already declared
```
### Related hiera yaml file:
```
cat rundeck.yaml:

rundeck::plugin:
    name: rundeck-ec2-nodes-plugin-1.5.jar
    source: https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/releases/download/1.5/rundeck-ec2-nodes-plugin-1.5.jar
```

### Related rundeck pp file:
```
  rundeck::config::plugin{ 'rundeck-ec2-nodes-plugin':
#    name   => 'rundeck-ec2-nodes-plugin-1.5.jar',
#    source => 'https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/releases/download/1.5/rundeck-ec2-nodes-plugin-1.5.jar'
     name => $::rundeck::plugin::name,
     source => $::rundeck::plugin::source
  }
```

If I give the name and source directly (commented in above pp code), code works fine and plugin is installed.

**Comment by liamjbennett** [comment] 2015-06-05 11:11
Are you sure the spacing in your yaml is correct?

I have been unable to reproduce this issue so I am closing for now.

**Closed by liamjbennett** 2015-06-05 11:11 UTC
Labels: bug
