### ISSUE TITLE
Ensure that puppet-archive dependency is correctly installed

### ISSUE THREAD

**Issue by liamjbennett** [puppet-community/puppet-rundeck#115] opened 2015-06-29 08:45 UTC
With the recent move to puppet-archive for downloading plugins it has been noticed (by @SydOps) that this dependency requires a gem to be installed on the puppet master. The documentation for states that it can be installed with `include archive`. This should be made clear from the documentation.

**Comment by jyaworski** [comment] 2015-11-21 05:29
Is this a duplicate of #131?

**Closed** 2015-11-21 07:45 UTC
